# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
fastlane_version "2.66.2"
default_platform :ios

platform :ios do
  before_all do     
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "cmnz-mjlf-wyoq-qnsv"
  end
  desc "Push a new beta build to TestFlight"
  lane :beta do
    cocoapods
    build_app(workspace: "Homesheff.xcworkspace", scheme: "Homesheff", export_options: {
                provisioningProfiles: {
                    "com.homesheff.appstore" => "HomeSheffAppstore",
                }
            })
    upload_to_testflight
  end
end
